// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLVatTu.Entity;

#nullable disable

namespace QLVatTu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230201035107_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLVatTu.Entity.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("ChiTietPhieuNhapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietPhieuNhapId"));

                    b.Property<int>("PhieuNhapId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.Property<int>("VaTuId")
                        .HasColumnType("int");

                    b.HasKey("ChiTietPhieuNhapId");

                    b.HasIndex("PhieuNhapId");

                    b.ToTable("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QLVatTu.Entity.ChiTietPhieuXuat", b =>
                {
                    b.Property<int>("ChiTietPhieuXuatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietPhieuXuatId"));

                    b.Property<int>("PhieuXuatId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongXuat")
                        .HasColumnType("int");

                    b.Property<int>("VaTuId")
                        .HasColumnType("int");

                    b.HasKey("ChiTietPhieuXuatId");

                    b.HasIndex("PhieuXuatId");

                    b.ToTable("ChiTietPhieuXuats");
                });

            modelBuilder.Entity("QLVatTu.Entity.PhieuNhap", b =>
                {
                    b.Property<int>("PhieuNhapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhieuNhapId"));

                    b.Property<int>("MaPhieu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhieuNhapId");

                    b.ToTable("PhieuNhaps");
                });

            modelBuilder.Entity("QLVatTu.Entity.PhieuXuat", b =>
                {
                    b.Property<int>("PhieuXuatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhieuXuatId"));

                    b.Property<int>("MaPhieu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhieuXuatId");

                    b.ToTable("PhieuXuats");
                });

            modelBuilder.Entity("QLVatTu.Entity.VatTu", b =>
                {
                    b.Property<int>("VatTuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VatTuId"));

                    b.Property<int?>("ChiTietPhieuNhapId")
                        .HasColumnType("int");

                    b.Property<int?>("ChiTietPhieuXuatId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenVatTu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VatTuId");

                    b.HasIndex("ChiTietPhieuNhapId");

                    b.HasIndex("ChiTietPhieuXuatId");

                    b.ToTable("VatTus");
                });

            modelBuilder.Entity("QLVatTu.Entity.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QLVatTu.Entity.PhieuNhap", "PhieuNhap")
                        .WithMany()
                        .HasForeignKey("PhieuNhapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("QLVatTu.Entity.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("QLVatTu.Entity.PhieuXuat", "PhieuXuat")
                        .WithMany()
                        .HasForeignKey("PhieuXuatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuXuat");
                });

            modelBuilder.Entity("QLVatTu.Entity.VatTu", b =>
                {
                    b.HasOne("QLVatTu.Entity.ChiTietPhieuNhap", null)
                        .WithMany("VatTus")
                        .HasForeignKey("ChiTietPhieuNhapId");

                    b.HasOne("QLVatTu.Entity.ChiTietPhieuXuat", null)
                        .WithMany("VatTus")
                        .HasForeignKey("ChiTietPhieuXuatId");
                });

            modelBuilder.Entity("QLVatTu.Entity.ChiTietPhieuNhap", b =>
                {
                    b.Navigation("VatTus");
                });

            modelBuilder.Entity("QLVatTu.Entity.ChiTietPhieuXuat", b =>
                {
                    b.Navigation("VatTus");
                });
#pragma warning restore 612, 618
        }
    }
}
